import Head from "next/head";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Navbar from "@/components/Navbar";
import { useAccount, useContract, useSigner } from "wagmi";
import TokenAbi from "@/ABIs/BuidlToken.json";
import NFTAbi from "@/ABIs/BuidlNFT.json";
import StakingAbi from "@/ABIs/Staking.json";
import { ethers } from "ethers";

export default function Home() {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const tokenContract = useContract({
    address: TokenAbi.address,
    abi: TokenAbi.abi,
    signerOrProvider: signer,
  });
  const nftContract = useContract({
    address: NFTAbi.address,
    abi: NFTAbi.abi,
    signerOrProvider: signer,
  });
  const stakingContract = useContract({
    address: StakingAbi.address,
    abi: StakingAbi.abi,
    signerOrProvider: signer,
  });
  // console.log(tokenContract);
  // console.log("nft", nftContract);
  // console.log("staking", stakingContract);
  return (
    <>
      <Head>
        <title>My staking dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button
          onClick={async () => {
            const tx = await tokenContract?.mintToken(
              address,
              ethers.utils.parseEther("10")
            );
            console.log(tx);
          }}
        >
          Get token
        </button>
      </main>
    </>
  );
}
