import Head from "next/head";
import { useAccount, useContract, useSigner } from "wagmi";
import TokenAbi from "@/ABIs/BuidlToken.json";
import StakingAbi from "@/ABIs/Staking.json";
import NFTAbi from "@/ABIs/BuidlNFT.json";
import TokenBal from "@/components/Modal/TokenBal";
import StakedNft from "@/components/Modal/StakedNft";
import UnstakedNft from "@/components/Modal/UnstakedNft";

export default function Home() {
  const { address } = useAccount();
  const { data: signer } = useSigner();
  const tokenContract = useContract({
    address: TokenAbi.address,
    abi: TokenAbi.abi,
    signerOrProvider: signer,
  });
  const nftContract = useContract({
    address: NFTAbi.address,
    abi: NFTAbi.abi,
    signerOrProvider: signer,
  });
  const stakingContract = useContract({
    address: StakingAbi.address,
    abi: StakingAbi.abi,
    signerOrProvider: signer,
  });

  return (
    <>
      <Head>
        <title>My staking dapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {address ? (
          <div>
            <TokenBal />
            <StakedNft />
            <UnstakedNft />
          </div>
        ) : (
          <div className="flex justify-center">
            <section className="px-5 border rounded-lg my-20 shadow-lg bg-[#0000009d]">
              <h2 className="text-2xl my-10">
                Connect wallet to get started !!
              </h2>
            </section>
          </div>
        )}
      </main>
    </>
  );
}
